# Generated by Django 3.0 on 2019-12-12 09:13

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rehsponse', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='rensponded_by',
            field=models.ManyToManyField(blank=True, related_name='responded_to', to=settings.AUTH_USER_MODEL),
        ),
    ]
