# Generated by Django 3.0 on 2019-12-10 06:33

from django.db import migrations, models
import rehsponse.validator


class Migration(migrations.Migration):

    dependencies = [
        ('rehsponse', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rehsponse',
            name='rehsponse_text',
            field=models.TextField(max_length=140, validators=[rehsponse.validator.validate_response]),
        ),
    ]
