# Generated by Django 3.0 on 2019-12-12 09:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rehsponse', '0002_userprofile_rensponded_by'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='rensponded_by',
            new_name='responded_by',
        ),
    ]
