# Generated by Django 3.0 on 2019-12-12 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rehsponse', '0005_contact'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='icon_name',
            field=models.CharField(default='fas fa-5x fa-stack-1x fa-book-open', max_length=120),
        ),
    ]
