# Generated by Django 3.0 on 2019-12-13 21:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rehsponse', '0006_contact_icon_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rehsponse',
            name='user_profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='poster', to=settings.AUTH_USER_MODEL),
        ),
    ]
