# Generated by Django 3.0 on 2019-12-14 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rehsponse', '0009_auto_20191214_1641'),
    ]

    operations = [
        migrations.AddField(
            model_name='rehsponse',
            name='reply',
            field=models.BooleanField(default=False, verbose_name='Is a reply?'),
        ),
    ]
