# Generated by Django 3.0 on 2019-12-16 15:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rehsponse', '0011_auto_20191216_2122'),
    ]

    operations = [
        migrations.AddField(
            model_name='rehsponse',
            name='reply_origin',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reply_to', to='rehsponse.Rehsponse'),
        ),
    ]
