# Generated by Django 3.0 on 2019-12-16 16:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rehsponse', '0012_rehsponse_reply_origin'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rehsponse',
            name='reply',
        ),
        migrations.RemoveField(
            model_name='rehsponse',
            name='reply_origin',
        ),
        migrations.AddField(
            model_name='rehsponse',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='rehsponse.Rehsponse'),
        ),
    ]
