# Generated by Django 3.0 on 2019-12-17 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rehsponse', '0014_auto_20191217_2217'),
    ]

    operations = [
        migrations.AddField(
            model_name='rehsponse',
            name='reply',
            field=models.BooleanField(default=False, verbose_name='Is a Reply ?'),
        ),
    ]
