# Generated by Django 3.0 on 2019-12-20 05:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rehsponse', '0016_auto_20191217_2239'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rehsponse',
            name='reply',
        ),
    ]
