# Generated by Django 3.0 on 2019-12-20 14:43

from django.db import migrations, models
import rehsponse.models


class Migration(migrations.Migration):

    dependencies = [
        ('rehsponse', '0020_auto_20191220_1956'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='height_field',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='user_image',
            field=models.ImageField(blank=True, height_field='height_field', null=True, upload_to=rehsponse.models.upload_location, width_field='width_field'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='width_field',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
